version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.25.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome:4.25.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    ports:
      - "6900:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_RETRY_INTERVAL=5
    networks:
      - selenium-network

  firefox:
    image: selenium/node-firefox:4.25.0
    container_name: firefox-node
    depends_on:
      - selenium-hub
    ports:
      - "6901:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_RETRY_INTERVAL=5
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
